language: python
python:
  - 3.8
  - 3.9
  - 3.10
  - 3.11
matrix:
  include:
    - python: 3.8
      dist: xenial
      sudo: required
script: nosetests tests
install:
  - pip install -r requirements.txt
  - pip install -r test_requirements.txt
notifications:
  email: false
